name: C/C++ CI

on:
  push:
    branches: [ "branchAutoTest" ]
  pull_request:
    branches: [ "branchAutoTest" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install automake and autoconf
      run: sudo apt-get update && sudo apt-get install -y automake autoconf

    - name: Generate missing files with Automake
      run: automake --add-missing

    - name: Run Autoconf
      run: autoreconf --install

    - name: Configure project
      run: ./configure

    - name: Build project
      run: make

    - name: Run tests
      run: cd ./tests && make check
